[package]
name = "glare-gemm-s8u8s32"
version = "0.1.0"
edition = "2021"

[dependencies]
glare-base = { path = "../glare-base" }
seq-macro = "0.3.5"
paste = "1.0.14"

[dev-dependencies]
glare-dev = { path = "../../crates/glare-dev" }

[features]
default = []
fuse = []