[package]
name = "bench"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
rand = "0.8.5"
corenum-base = { path = "../../crates/corenum-base" }
corenum-gemm-f32 = { path = "../../crates/corenum-gemm-f32" }
corenum-gemm-f16 = { path = "../../crates/corenum-gemm-f16" }
# corenum-dev = { path = "../../crates/corenum-dev" }
clap = {version = "~4.0", features = ["unicode", "derive"] }
gemm = {git = "https://github.com/sarah-ek/gemm", optional = true }
half = { version = "2.4.1", features = ["rand_distr", "num-traits"] }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "bench"
harness = false



[features]
default = []
mkl_check = []
mkl = []
blis = []
blasfeo = []
corenum = []
rustgemm = ["dep:gemm"]