[package]
name = "glar-gemm-s8u8s32"
version = "0.1.0"
edition = "2021"

[dependencies]
glar-base = { path = "../glar-base" }
seq-macro = "0.3.5"
paste = "1.0.14"

[dev-dependencies]
glar-dev = { path = "../../crates/glar-dev" }

[features]
default = []
fuse = []