# [build]
# target = "aarch64-pc-windows-gnullvm"
# target = "aarch64-unknown-linux-gnu"
# target = "x86_64-pc-windows-gnu"

# [target.aarch64-unknown-linux-gnu]
# linker = "rust-lld"
# [build]
# rustflags = ["-C", "target-feature=+avx2,+avx"]