[workspace]

members = [ 
    "corenum-base", 
    "corenum-dev", "corenum-gemm-f16",
    "corenum-gemm-f32", "corenum-gemm-f64",
    "corenum-gemm-c32", "corenum-gemm-c64",
    "corenum-gemm-s16s16s32"
]

resolver = "2"
