[workspace]
members = [ 
    "glar-base", 
    "glar-dev", "glar-gemm-f16",
    "glar-gemm-f32", "glar-gemm-f64",
    "glar-gemm-c32", "glar-gemm-c64",
    "glar-gemm-s16s16s32"
, "glar-gemm-s8u8s32"]

[workspace.dependencies]


resolver = "2"
